[theme]
# Primary accent color for interactive elements.
primaryColor = "#E694FF"

# Background color for the main content area.
backgroundColor = "#66ff33"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#a6ff4d"

# Color used for almost all text.
textColor = "#000000"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"
